spring.application.name=todo

# lê as configurações do arquivo .env
spring.config.import=optional:file:.env[.properties]

# conexão com o banco usando variáveis
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:todo_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

# comandos para acompanharmos o que o frame hibernate java está fazendo no banco de dados
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true